/*
 * Stub for class it.feio.android.omninotes.dcap.OmniNotesManager
 * Generated by Sapphire Compiler (sc).
 */
package it.feio.android.omninotes.dcap.stubs;


public final class OmniNotesManager_Stub extends it.feio.android.omninotes.dcap.OmniNotesManager implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public OmniNotesManager_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of getDbHelper()
    public it.feio.android.omninotes.db.DbHelper getDbHelper() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getDbHelper();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public it.feio.android.omninotes.db.DbHelper it.feio.android.omninotes.dcap.OmniNotesManager.getDbHelper()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((it.feio.android.omninotes.db.DbHelper) $__result);
    }
}
