/*
 * Stub for class it.feio.android.omninotes.dcap.OmniNotesManager
 * Generated by Sapphire Compiler (sc).
 */
package it.feio.android.omninotes.dcap.stubs;


public final class OmniNotesManager_Stub extends it.feio.android.omninotes.dcap.OmniNotesManager implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public OmniNotesManager_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }


}
