/*
 * Stub for class it.feio.android.omninotes.models.Attachment
 * Generated by Sapphire Compiler (sc).
 */
package it.feio.android.omninotes.models.stubs;


public final class Attachment_Stub extends it.feio.android.omninotes.models.Attachment implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public Attachment_Stub (android.net.Uri $param_Uri_1, java.lang.String $param_String_2) {
        super($param_Uri_1, $param_String_2);
    }

    public Attachment_Stub (long $param_long_1, android.net.Uri $param_Uri_2, java.lang.String $param_String_3, long $param_long_4, long $param_long_5, java.lang.String $param_String_6) {
        super($param_long_1, $param_Uri_2, $param_String_3, $param_long_4, $param_long_5, $param_String_6);
    }

    public Attachment_Stub (it.feio.android.omninotes.commons.models.BaseAttachment $param_BaseAttachment_1) {
        super($param_BaseAttachment_1);
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of writeToParcel(Parcel, int)
    public void writeToParcel(android.os.Parcel $param_Parcel_1, int $param_int_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.writeToParcel( $param_Parcel_1,  $param_int_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void it.feio.android.omninotes.models.Attachment.writeToParcel(android.os.Parcel,int)";
                $__params.add($param_Parcel_1);
                $__params.add($param_int_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of setUri(Uri)
    public void setUri(android.net.Uri $param_Uri_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.setUri( $param_Uri_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void it.feio.android.omninotes.models.Attachment.setUri(android.net.Uri)";
                $__params.add($param_Uri_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of getUri()
    public android.net.Uri getUri() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getUri();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public android.net.Uri it.feio.android.omninotes.models.Attachment.getUri()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((android.net.Uri) $__result);
    }

    // Implementation of describeContents()
    public int describeContents() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.describeContents();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public int it.feio.android.omninotes.models.Attachment.describeContents()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Integer) $__result).intValue();
    }
}
