/*
 * Stub for class it.feio.android.omninotes.models.Note
 * Generated by Sapphire Compiler (sc).
 */
package it.feio.android.omninotes.models.stubs;


public final class Note_Stub extends it.feio.android.omninotes.models.Note implements sapphire.common.AppObjectStub {
    // SUID
    static final long serialVersionUID =-7612567897010931666L;

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public Note_Stub (java.lang.Long $param_Long_1, java.lang.Long $param_Long_2, java.lang.String $param_String_3, java.lang.String $param_String_4, java.lang.Integer $param_Integer_5, java.lang.Integer $param_Integer_6, java.lang.String $param_String_7, java.lang.String $param_String_8, java.lang.Integer $param_Integer_9, java.lang.String $param_String_10, java.lang.String $param_String_11, it.feio.android.omninotes.models.Category $param_Category_12, java.lang.Integer $param_Integer_13, java.lang.Integer $param_Integer_14) {
        super($param_Long_1, $param_Long_2, $param_String_3, $param_String_4, $param_Integer_5, $param_Integer_6, $param_String_7, $param_String_8, $param_Integer_9, $param_String_10, $param_String_11, $param_Category_12, $param_Integer_13, $param_Integer_14);
    }

    public Note_Stub (it.feio.android.omninotes.models.Note $param_Note_1) {
        super($param_Note_1);
    }

    public Note_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of writeToParcel(Parcel, int)
    public void writeToParcel(android.os.Parcel $param_Parcel_1, int $param_int_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.writeToParcel( $param_Parcel_1,  $param_int_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void it.feio.android.omninotes.models.Note.writeToParcel(android.os.Parcel,int)";
                $__params.add($param_Parcel_1);
                $__params.add($param_int_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of setPasswordChecked(boolean)
    public void setPasswordChecked(boolean $param_boolean_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.setPasswordChecked( $param_boolean_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void it.feio.android.omninotes.models.Note.setPasswordChecked(boolean)";
                $__params.add($param_boolean_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of setCategory(Category)
    public void setCategory(it.feio.android.omninotes.models.Category $param_Category_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.setCategory( $param_Category_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void it.feio.android.omninotes.models.Note.setCategory(it.feio.android.omninotes.models.Category)";
                $__params.add($param_Category_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of setAttachmentsListOld(ArrayList)
    public void setAttachmentsListOld(java.util.ArrayList $param_ArrayList_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.setAttachmentsListOld( $param_ArrayList_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void it.feio.android.omninotes.models.Note.setAttachmentsListOld(java.util.ArrayList<it.feio.android.omninotes.models.Attachment>)";
                $__params.add($param_ArrayList_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of setAttachmentsList(ArrayList)
    public void setAttachmentsList(java.util.ArrayList $param_ArrayList_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.setAttachmentsList( $param_ArrayList_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void it.feio.android.omninotes.models.Note.setAttachmentsList(java.util.ArrayList<it.feio.android.omninotes.models.Attachment>)";
                $__params.add($param_ArrayList_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of removeAttachment(Attachment)
    public void removeAttachment(it.feio.android.omninotes.models.Attachment $param_Attachment_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.removeAttachment( $param_Attachment_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void it.feio.android.omninotes.models.Note.removeAttachment(it.feio.android.omninotes.models.Attachment)";
                $__params.add($param_Attachment_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of isPasswordChecked()
    public boolean isPasswordChecked() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.isPasswordChecked();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boolean it.feio.android.omninotes.models.Note.isPasswordChecked()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Boolean) $__result).booleanValue();
    }

    // Implementation of getCategory()
    public it.feio.android.omninotes.models.Category getCategory() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getCategory();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public it.feio.android.omninotes.models.Category it.feio.android.omninotes.models.Note.getCategory()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((it.feio.android.omninotes.models.Category) $__result);
    }

    // Implementation of getAttachmentsListOld()
    public java.util.List getAttachmentsListOld() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getAttachmentsListOld();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Attachment> it.feio.android.omninotes.models.Note.getAttachmentsListOld()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of getAttachmentsList()
    public java.util.List getAttachmentsList() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getAttachmentsList();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Attachment> it.feio.android.omninotes.models.Note.getAttachmentsList()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of describeContents()
    public int describeContents() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.describeContents();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public int it.feio.android.omninotes.models.Note.describeContents()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Integer) $__result).intValue();
    }

    // Implementation of addAttachment(Attachment)
    public void addAttachment(it.feio.android.omninotes.models.Attachment $param_Attachment_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.addAttachment( $param_Attachment_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void it.feio.android.omninotes.models.Note.addAttachment(it.feio.android.omninotes.models.Attachment)";
                $__params.add($param_Attachment_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
