/*
 * Stub for class it.feio.android.omninotes.db.DbHelper
 * Generated by Sapphire Compiler (sc).
 */
package it.feio.android.omninotes.db.stubs;


public final class DbHelper_Stub extends it.feio.android.omninotes.db.DbHelper implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public DbHelper_Stub (android.content.Context $param_Context_1) {
        super($param_Context_1);
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of updateNote(Note, boolean)
    public it.feio.android.omninotes.models.Note updateNote(it.feio.android.omninotes.models.Note $param_Note_1, boolean $param_boolean_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.updateNote( $param_Note_1,  $param_boolean_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public it.feio.android.omninotes.models.Note it.feio.android.omninotes.db.DbHelper.updateNote(it.feio.android.omninotes.models.Note,boolean)";
                $__params.add($param_Note_1);
                $__params.add($param_boolean_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((it.feio.android.omninotes.models.Note) $__result);
    }

    // Implementation of updateCategory(Category)
    public it.feio.android.omninotes.models.Category updateCategory(it.feio.android.omninotes.models.Category $param_Category_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.updateCategory( $param_Category_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public it.feio.android.omninotes.models.Category it.feio.android.omninotes.db.DbHelper.updateCategory(it.feio.android.omninotes.models.Category)";
                $__params.add($param_Category_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((it.feio.android.omninotes.models.Category) $__result);
    }

    // Implementation of updateAttachment(long, Attachment, SQLiteDatabase)
    public it.feio.android.omninotes.models.Attachment updateAttachment(long $param_long_1, it.feio.android.omninotes.models.Attachment $param_Attachment_2, android.database.sqlite.SQLiteDatabase $param_SQLiteDatabase_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.updateAttachment( $param_long_1,  $param_Attachment_2,  $param_SQLiteDatabase_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public it.feio.android.omninotes.models.Attachment it.feio.android.omninotes.db.DbHelper.updateAttachment(long,it.feio.android.omninotes.models.Attachment,android.database.sqlite.SQLiteDatabase)";
                $__params.add($param_long_1);
                $__params.add($param_Attachment_2);
                $__params.add($param_SQLiteDatabase_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((it.feio.android.omninotes.models.Attachment) $__result);
    }

    // Implementation of updateAttachment(Attachment)
    public it.feio.android.omninotes.models.Attachment updateAttachment(it.feio.android.omninotes.models.Attachment $param_Attachment_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.updateAttachment( $param_Attachment_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public it.feio.android.omninotes.models.Attachment it.feio.android.omninotes.db.DbHelper.updateAttachment(it.feio.android.omninotes.models.Attachment)";
                $__params.add($param_Attachment_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((it.feio.android.omninotes.models.Attachment) $__result);
    }

    // Implementation of trashNote(Note, boolean)
    public void trashNote(it.feio.android.omninotes.models.Note $param_Note_1, boolean $param_boolean_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.trashNote( $param_Note_1,  $param_boolean_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void it.feio.android.omninotes.db.DbHelper.trashNote(it.feio.android.omninotes.models.Note,boolean)";
                $__params.add($param_Note_1);
                $__params.add($param_boolean_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of setReminderFired(long, boolean)
    public void setReminderFired(long $param_long_1, boolean $param_boolean_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.setReminderFired( $param_long_1,  $param_boolean_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void it.feio.android.omninotes.db.DbHelper.setReminderFired(long,boolean)";
                $__params.add($param_long_1);
                $__params.add($param_boolean_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of onUpgrade(SQLiteDatabase, int, int)
    public void onUpgrade(android.database.sqlite.SQLiteDatabase $param_SQLiteDatabase_1, int $param_int_2, int $param_int_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.onUpgrade( $param_SQLiteDatabase_1,  $param_int_2,  $param_int_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void it.feio.android.omninotes.db.DbHelper.onUpgrade(android.database.sqlite.SQLiteDatabase,int,int)";
                $__params.add($param_SQLiteDatabase_1);
                $__params.add($param_int_2);
                $__params.add($param_int_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of onCreate(SQLiteDatabase)
    public void onCreate(android.database.sqlite.SQLiteDatabase $param_SQLiteDatabase_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.onCreate( $param_SQLiteDatabase_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void it.feio.android.omninotes.db.DbHelper.onCreate(android.database.sqlite.SQLiteDatabase)";
                $__params.add($param_SQLiteDatabase_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of getWords(Note)
    public int getWords(it.feio.android.omninotes.models.Note $param_Note_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getWords( $param_Note_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public int it.feio.android.omninotes.db.DbHelper.getWords(it.feio.android.omninotes.models.Note)";
                $__params.add($param_Note_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Integer) $__result).intValue();
    }

    // Implementation of getTodayReminders()
    public java.util.List getTodayReminders() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getTodayReminders();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Note> it.feio.android.omninotes.db.DbHelper.getTodayReminders()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of getTags(Note)
    public java.util.List getTags(it.feio.android.omninotes.models.Note $param_Note_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getTags( $param_Note_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Tag> it.feio.android.omninotes.db.DbHelper.getTags(it.feio.android.omninotes.models.Note)";
                $__params.add($param_Note_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of getTags()
    public java.util.List getTags() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getTags();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Tag> it.feio.android.omninotes.db.DbHelper.getTags()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of getStats()
    public it.feio.android.omninotes.models.Stats getStats() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getStats();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public it.feio.android.omninotes.models.Stats it.feio.android.omninotes.db.DbHelper.getStats()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((it.feio.android.omninotes.models.Stats) $__result);
    }

    // Implementation of getNotesWithReminderNotFired()
    public java.util.List getNotesWithReminderNotFired() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getNotesWithReminderNotFired();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Note> it.feio.android.omninotes.db.DbHelper.getNotesWithReminderNotFired()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of getNotesWithReminder(boolean)
    public java.util.List getNotesWithReminder(boolean $param_boolean_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getNotesWithReminder( $param_boolean_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Note> it.feio.android.omninotes.db.DbHelper.getNotesWithReminder(boolean)";
                $__params.add($param_boolean_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of getNotesWithLock(boolean)
    public java.util.List getNotesWithLock(boolean $param_boolean_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getNotesWithLock( $param_boolean_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Note> it.feio.android.omninotes.db.DbHelper.getNotesWithLock(boolean)";
                $__params.add($param_boolean_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of getNotesWithLocation()
    public java.util.List getNotesWithLocation() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getNotesWithLocation();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Note> it.feio.android.omninotes.db.DbHelper.getNotesWithLocation()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of getNotesUncategorized()
    public java.util.List getNotesUncategorized() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getNotesUncategorized();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Note> it.feio.android.omninotes.db.DbHelper.getNotesUncategorized()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of getNotesTrashed()
    public java.util.List getNotesTrashed() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getNotesTrashed();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Note> it.feio.android.omninotes.db.DbHelper.getNotesTrashed()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of getNotesByTag(String[])
    public java.util.List getNotesByTag(java.lang.String[] $param_arrayOf_String_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getNotesByTag( $param_arrayOf_String_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Note> it.feio.android.omninotes.db.DbHelper.getNotesByTag(java.lang.String[])";
                $__params.add($param_arrayOf_String_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of getNotesByTag(String)
    public java.util.List getNotesByTag(java.lang.String $param_String_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getNotesByTag( $param_String_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Note> it.feio.android.omninotes.db.DbHelper.getNotesByTag(java.lang.String)";
                $__params.add($param_String_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of getNotesByPattern(String)
    public java.util.List getNotesByPattern(java.lang.String $param_String_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getNotesByPattern( $param_String_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Note> it.feio.android.omninotes.db.DbHelper.getNotesByPattern(java.lang.String)";
                $__params.add($param_String_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of getNotesByCategory(Long)
    public java.util.List getNotesByCategory(java.lang.Long $param_Long_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getNotesByCategory( $param_Long_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Note> it.feio.android.omninotes.db.DbHelper.getNotesByCategory(java.lang.Long)";
                $__params.add($param_Long_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of getNotesArchived()
    public java.util.List getNotesArchived() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getNotesArchived();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Note> it.feio.android.omninotes.db.DbHelper.getNotesArchived()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of getNotesActive()
    public java.util.List getNotesActive() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getNotesActive();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Note> it.feio.android.omninotes.db.DbHelper.getNotesActive()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of getNotes(String, boolean)
    public java.util.List getNotes(java.lang.String $param_String_1, boolean $param_boolean_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getNotes( $param_String_1,  $param_boolean_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Note> it.feio.android.omninotes.db.DbHelper.getNotes(java.lang.String,boolean)";
                $__params.add($param_String_1);
                $__params.add($param_boolean_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of getNoteAttachments(Note)
    public java.util.ArrayList getNoteAttachments(it.feio.android.omninotes.models.Note $param_Note_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getNoteAttachments( $param_Note_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.ArrayList<it.feio.android.omninotes.models.Attachment> it.feio.android.omninotes.db.DbHelper.getNoteAttachments(it.feio.android.omninotes.models.Note)";
                $__params.add($param_Note_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.ArrayList) $__result);
    }

    // Implementation of getNote(long)
    public it.feio.android.omninotes.models.Note getNote(long $param_long_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getNote( $param_long_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public it.feio.android.omninotes.models.Note it.feio.android.omninotes.db.DbHelper.getNote(long)";
                $__params.add($param_long_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((it.feio.android.omninotes.models.Note) $__result);
    }

    // Implementation of getMasked()
    public java.util.List getMasked() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getMasked();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Note> it.feio.android.omninotes.db.DbHelper.getMasked()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }
    

    // Implementation of getDatabaseName()
    public java.lang.String getDatabaseName() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getDatabaseName();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.lang.String it.feio.android.omninotes.db.DbHelper.getDatabaseName()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.String) $__result);
    }

    // Implementation of getDatabase(boolean)
    public android.database.sqlite.SQLiteDatabase getDatabase(boolean $param_boolean_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getDatabase( $param_boolean_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public android.database.sqlite.SQLiteDatabase it.feio.android.omninotes.db.DbHelper.getDatabase(boolean)";
                $__params.add($param_boolean_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((android.database.sqlite.SQLiteDatabase) $__result);
    }

    // Implementation of getDatabase()
    public android.database.sqlite.SQLiteDatabase getDatabase() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getDatabase();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public android.database.sqlite.SQLiteDatabase it.feio.android.omninotes.db.DbHelper.getDatabase()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((android.database.sqlite.SQLiteDatabase) $__result);
    }

    // Implementation of getChecklists()
    public java.util.List getChecklists() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getChecklists();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Note> it.feio.android.omninotes.db.DbHelper.getChecklists()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of getChars(Note)
    public int getChars(it.feio.android.omninotes.models.Note $param_Note_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getChars( $param_Note_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public int it.feio.android.omninotes.db.DbHelper.getChars(it.feio.android.omninotes.models.Note)";
                $__params.add($param_Note_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Integer) $__result).intValue();
    }

    // Implementation of getCategory(Long)
    public it.feio.android.omninotes.models.Category getCategory(java.lang.Long $param_Long_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getCategory( $param_Long_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public it.feio.android.omninotes.models.Category it.feio.android.omninotes.db.DbHelper.getCategory(java.lang.Long)";
                $__params.add($param_Long_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((it.feio.android.omninotes.models.Category) $__result);
    }

    // Implementation of getCategorizedCount(Category)
    public int getCategorizedCount(it.feio.android.omninotes.models.Category $param_Category_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getCategorizedCount( $param_Category_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public int it.feio.android.omninotes.db.DbHelper.getCategorizedCount(it.feio.android.omninotes.models.Category)";
                $__params.add($param_Category_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Integer) $__result).intValue();
    }

    // Implementation of getCategories()
    public java.util.ArrayList getCategories() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getCategories();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.ArrayList<it.feio.android.omninotes.models.Category> it.feio.android.omninotes.db.DbHelper.getCategories()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.ArrayList) $__result);
    }

    // Implementation of getAttachments(String)
    public java.util.ArrayList getAttachments(java.lang.String $param_String_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getAttachments( $param_String_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.ArrayList<it.feio.android.omninotes.models.Attachment> it.feio.android.omninotes.db.DbHelper.getAttachments(java.lang.String)";
                $__params.add($param_String_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.ArrayList) $__result);
    }

    // Implementation of getAllNotes(Boolean)
    public java.util.List getAllNotes(java.lang.Boolean $param_Boolean_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getAllNotes( $param_Boolean_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<it.feio.android.omninotes.models.Note> it.feio.android.omninotes.db.DbHelper.getAllNotes(java.lang.Boolean)";
                $__params.add($param_Boolean_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of getAllAttachments()
    public java.util.ArrayList getAllAttachments() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getAllAttachments();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.ArrayList<it.feio.android.omninotes.models.Attachment> it.feio.android.omninotes.db.DbHelper.getAllAttachments()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.ArrayList) $__result);
    }

    // Implementation of emptyTrash()
    public void emptyTrash() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.emptyTrash();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void it.feio.android.omninotes.db.DbHelper.emptyTrash()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of deleteNote(Note, boolean)
    public boolean deleteNote(it.feio.android.omninotes.models.Note $param_Note_1, boolean $param_boolean_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.deleteNote( $param_Note_1,  $param_boolean_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boolean it.feio.android.omninotes.db.DbHelper.deleteNote(it.feio.android.omninotes.models.Note,boolean)";
                $__params.add($param_Note_1);
                $__params.add($param_boolean_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Boolean) $__result).booleanValue();
    }

    // Implementation of deleteNote(Note)
    public boolean deleteNote(it.feio.android.omninotes.models.Note $param_Note_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.deleteNote( $param_Note_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boolean it.feio.android.omninotes.db.DbHelper.deleteNote(it.feio.android.omninotes.models.Note)";
                $__params.add($param_Note_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Boolean) $__result).booleanValue();
    }

    // Implementation of deleteCategory(Category)
    public long deleteCategory(it.feio.android.omninotes.models.Category $param_Category_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.deleteCategory( $param_Category_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public long it.feio.android.omninotes.db.DbHelper.deleteCategory(it.feio.android.omninotes.models.Category)";
                $__params.add($param_Category_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Long) $__result).longValue();
    }

    // Implementation of archiveNote(Note, boolean)
    public void archiveNote(it.feio.android.omninotes.models.Note $param_Note_1, boolean $param_boolean_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.archiveNote( $param_Note_1,  $param_boolean_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void it.feio.android.omninotes.db.DbHelper.archiveNote(it.feio.android.omninotes.models.Note,boolean)";
                $__params.add($param_Note_1);
                $__params.add($param_boolean_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
